export type EnergySupplyProduct = 'crude' | 'lng' | 'products';
export type EnergySupplierRegion = 'gulf' | 'russia' | 'usa' | 'africa' | 'americas' | 'europe' | 'east_asia' | 'southeast_asia';

export interface EnergyNetworkNode {
  id: string;
  name: string;
  countryCode: string;
  role: 'importer' | 'supplier';
  region: EnergySupplierRegion | 'india' | 'china' | 'japan' | 'south_korea' | 'eu' | 'taiwan' | 'thailand' | 'vietnam';
  lat: number;
  lon: number;
}

export interface EnergySupplyRoute {
  id: string;
  supplierId: string;
  importerId: string;
  product: EnergySupplyProduct;
  dependencyPct: number;
  routeExposure: number;
  corridor: string;
  chokepoints: string[];
  waypointPositions: Array<[number, number]>;
  notes: string;
}

export const ENERGY_NETWORK_NODES: readonly EnergyNetworkNode[] = [
  { id: 'india', name: 'India', countryCode: 'IN', role: 'importer', region: 'india', lat: 20.6, lon: 78.9 },
  { id: 'china', name: 'China', countryCode: 'CN', role: 'importer', region: 'china', lat: 35.9, lon: 104.2 },
  { id: 'japan', name: 'Japan', countryCode: 'JP', role: 'importer', region: 'japan', lat: 36.2, lon: 138.3 },
  { id: 'south_korea', name: 'South Korea', countryCode: 'KR', role: 'importer', region: 'south_korea', lat: 35.9, lon: 127.8 },
  { id: 'eu', name: 'European Union', countryCode: 'EU', role: 'importer', region: 'eu', lat: 50.1, lon: 10.5 },
  { id: 'taiwan', name: 'Taiwan', countryCode: 'TW', role: 'importer', region: 'taiwan', lat: 23.7, lon: 120.9 },
  { id: 'thailand', name: 'Thailand', countryCode: 'TH', role: 'importer', region: 'thailand', lat: 15.9, lon: 100.9 },
  { id: 'vietnam', name: 'Vietnam', countryCode: 'VN', role: 'importer', region: 'vietnam', lat: 14.1, lon: 108.3 },
  { id: 'saudi_arabia', name: 'Saudi Arabia', countryCode: 'SA', role: 'supplier', region: 'gulf', lat: 24.7, lon: 46.7 },
  { id: 'uae', name: 'UAE', countryCode: 'AE', role: 'supplier', region: 'gulf', lat: 24.5, lon: 54.4 },
  { id: 'iraq', name: 'Iraq', countryCode: 'IQ', role: 'supplier', region: 'gulf', lat: 33.3, lon: 44.4 },
  { id: 'qatar', name: 'Qatar', countryCode: 'QA', role: 'supplier', region: 'gulf', lat: 25.4, lon: 51.2 },
  { id: 'kuwait', name: 'Kuwait', countryCode: 'KW', role: 'supplier', region: 'gulf', lat: 29.3, lon: 47.5 },
  { id: 'oman', name: 'Oman', countryCode: 'OM', role: 'supplier', region: 'gulf', lat: 21.5, lon: 55.9 },
  { id: 'russia', name: 'Russia', countryCode: 'RU', role: 'supplier', region: 'russia', lat: 55.8, lon: 37.6 },
  { id: 'usa', name: 'USA', countryCode: 'US', role: 'supplier', region: 'usa', lat: 29.8, lon: -95.0 },
  { id: 'africa', name: 'African suppliers', countryCode: 'AF', role: 'supplier', region: 'africa', lat: 6.5, lon: 3.4 },
  { id: 'norway', name: 'Norway', countryCode: 'NO', role: 'supplier', region: 'europe', lat: 60.5, lon: 8.5 },
  { id: 'brazil', name: 'Brazil', countryCode: 'BR', role: 'supplier', region: 'americas', lat: -14.2, lon: -51.9 },
];

export const ENERGY_SUPPLY_ROUTES: readonly EnergySupplyRoute[] = [
  // India routes (existing)
  {
    id: 'russia-india-crude',
    supplierId: 'russia',
    importerId: 'india',
    product: 'crude',
    dependencyPct: 35,
    routeExposure: 58,
    corridor: 'Baltic / Black Sea / Arctic loaders to west coast India',
    chokepoints: ['bosphorus', 'suez', 'bab_el_mandeb'],
    waypointPositions: [[37.6, 55.8], [29.0, 41.1], [32.3, 30.5], [43.3, 12.5], [72.9, 18.9]],
    notes: 'Long-haul sanctioned-origin exposure; insurance, fleet availability, and payment rails drive disruption sensitivity.',
  },
  {
    id: 'iraq-india-crude',
    supplierId: 'iraq',
    importerId: 'india',
    product: 'crude',
    dependencyPct: 21,
    routeExposure: 72,
    corridor: 'Basra to west coast India via Strait of Hormuz',
    chokepoints: ['hormuz_strait'],
    waypointPositions: [[48.5, 30.5], [56.5, 26.5], [72.9, 18.9]],
    notes: 'Core Gulf crude exposure; highly sensitive to Hormuz closure, war-risk premiums, and tanker queueing.',
  },
  {
    id: 'saudi-india-crude',
    supplierId: 'saudi_arabia',
    importerId: 'india',
    product: 'crude',
    dependencyPct: 15,
    routeExposure: 70,
    corridor: 'Ras Tanura / Yanbu to west coast India',
    chokepoints: ['hormuz_strait'],
    waypointPositions: [[50.2, 26.6], [56.5, 26.5], [72.9, 18.9]],
    notes: 'Strategic supplier with high route concentration through Gulf sea lanes for eastern export flows.',
  },
  {
    id: 'uae-india-crude-products',
    supplierId: 'uae',
    importerId: 'india',
    product: 'products',
    dependencyPct: 8,
    routeExposure: 68,
    corridor: 'Jebel Ali / Fujairah to west coast India',
    chokepoints: ['hormuz_strait'],
    waypointPositions: [[54.4, 24.5], [56.5, 26.5], [72.9, 18.9]],
    notes: 'Short-haul Gulf route; lower distance but concentrated around Gulf escalation and insurance pricing.',
  },
  {
    id: 'usa-india-crude-lng',
    supplierId: 'usa',
    importerId: 'india',
    product: 'lng',
    dependencyPct: 10,
    routeExposure: 44,
    corridor: 'US Gulf Coast to India via Cape / Suez options',
    chokepoints: ['cape_of_good_hope', 'suez', 'bab_el_mandeb'],
    waypointPositions: [[-95.0, 29.8], [-5.6, 35.9], [32.3, 30.5], [43.3, 12.5], [72.9, 18.9]],
    notes: 'Diversification value is high; route choice shifts between Suez and Cape depending on Red Sea risk and freight economics.',
  },
  {
    id: 'africa-india-crude-lng',
    supplierId: 'africa',
    importerId: 'india',
    product: 'crude',
    dependencyPct: 11,
    routeExposure: 46,
    corridor: 'Nigeria / Angola / Mozambique loaders to India',
    chokepoints: ['cape_of_good_hope'],
    waypointPositions: [[3.4, 6.5], [18.5, -34.4], [72.9, 18.9]],
    notes: 'African barrels and LNG diversify Gulf exposure but add weather, port reliability, and long-haul freight sensitivity.',
  },
  // China routes
  {
    id: 'saudi-china-crude',
    supplierId: 'saudi_arabia',
    importerId: 'china',
    product: 'crude',
    dependencyPct: 18,
    routeExposure: 72,
    corridor: 'Ras Tanura to east coast China via Strait of Hormuz',
    chokepoints: ['hormuz_strait', 'malacca_strait'],
    waypointPositions: [[50.2, 26.6], [56.5, 26.5], [99.5, 4.0], [120.5, 22.0]],
    notes: 'Core Gulf crude exposure; highly sensitive to Hormuz closure and Malacca congestion.',
  },
  {
    id: 'russia-china-crude',
    supplierId: 'russia',
    importerId: 'china',
    product: 'crude',
    dependencyPct: 16,
    routeExposure: 35,
    corridor: 'ESPO pipeline and Far East loaders to northeast China',
    chokepoints: ['bosphorus'],
    waypointPositions: [[55.8, 37.6], [132.0, 43.0], [120.0, 40.0]],
    notes: 'Pipeline reduces maritime risk but Eastern Sea Board loaders still expose to Pacific weather and sanctions.',
  },
  {
    id: 'africa-china-crude',
    supplierId: 'africa',
    importerId: 'china',
    product: 'crude',
    dependencyPct: 15,
    routeExposure: 52,
    corridor: 'Nigeria / Angola to east coast China via Cape',
    chokepoints: ['cape_of_good_hope', 'malacca_strait'],
    waypointPositions: [[3.4, 6.5], [18.5, -34.4], [99.5, 4.0], [120.5, 22.0]],
    notes: 'Long-haul African barrels; Cape route avoids Red Sea risk but adds freight cost.',
  },
  {
    id: 'qatar-china-lng',
    supplierId: 'qatar',
    importerId: 'china',
    product: 'lng',
    dependencyPct: 12,
    routeExposure: 68,
    corridor: 'Ras Laffan to east coast China via Strait of Hormuz',
    chokepoints: ['hormuz_strait', 'malacca_strait'],
    waypointPositions: [[51.2, 25.4], [56.5, 26.5], [99.5, 4.0], [120.5, 22.0]],
    notes: 'Qatar LNG is critical for Chinese gas security; highly sensitive to Hormuz closure.',
  },
  {
    id: 'usa-china-lng',
    supplierId: 'usa',
    importerId: 'china',
    product: 'lng',
    dependencyPct: 8,
    routeExposure: 42,
    corridor: 'US Gulf Coast to China via Panama Canal',
    chokepoints: ['panama_canal', 'malacca_strait'],
    waypointPositions: [[-95.0, 29.8], [-80.0, 9.0], [120.0, 15.0], [120.5, 22.0]],
    notes: 'Diversification route; Panama Canal draft restrictions and Malacca congestion are key risks.',
  },
  // Japan routes
  {
    id: 'saudi-japan-crude',
    supplierId: 'saudi_arabia',
    importerId: 'japan',
    product: 'crude',
    dependencyPct: 35,
    routeExposure: 75,
    corridor: 'Ras Tanura / Yanbu to Japanese refineries via Strait of Hormuz',
    chokepoints: ['hormuz_strait', 'malacca_strait'],
    waypointPositions: [[50.2, 26.6], [56.5, 26.5], [99.5, 4.0], [135.0, 34.0]],
    notes: 'Core Gulf crude for Japanese refineries; extreme sensitivity to Hormuz closure.',
  },
  {
    id: 'uae-japan-crude',
    supplierId: 'uae',
    importerId: 'japan',
    product: 'crude',
    dependencyPct: 15,
    routeExposure: 70,
    corridor: 'Fujairah to Japanese refineries via Malacca',
    chokepoints: ['hormuz_strait', 'malacca_strait'],
    waypointPositions: [[54.4, 24.5], [99.5, 4.0], [135.0, 34.0]],
    notes: 'UAE crude is major Japanese import; dual chokepoint exposure.',
  },
  {
    id: 'qatar-japan-lng',
    supplierId: 'qatar',
    importerId: 'japan',
    product: 'lng',
    dependencyPct: 10,
    routeExposure: 65,
    corridor: 'Ras Laffan to Japanese LNG terminals via Hormuz',
    chokepoints: ['hormuz_strait', 'malacca_strait'],
    waypointPositions: [[51.2, 25.4], [56.5, 26.5], [99.5, 4.0], [135.0, 34.0]],
    notes: 'Qatar LNG is key for Japanese gas security; dual chokepoint exposure.',
  },
  // South Korea routes
  {
    id: 'saudi-south_korea-crude',
    supplierId: 'saudi_arabia',
    importerId: 'south_korea',
    product: 'crude',
    dependencyPct: 30,
    routeExposure: 73,
    corridor: 'Ras Tanura to Korean refineries via Strait of Hormuz',
    chokepoints: ['hormuz_strait', 'malacca_strait'],
    waypointPositions: [[50.2, 26.6], [56.5, 26.5], [99.5, 4.0], [129.0, 35.0]],
    notes: 'Core Gulf crude for Korean refineries; extreme sensitivity to Hormuz closure.',
  },
  {
    id: 'kuwait-south_korea-crude',
    supplierId: 'kuwait',
    importerId: 'south_korea',
    product: 'crude',
    dependencyPct: 15,
    routeExposure: 78,
    corridor: 'Mina Al Ahmadi to Korean refineries via Strait of Hormuz',
    chokepoints: ['hormuz_strait', 'malacca_strait'],
    waypointPositions: [[47.9, 29.4], [56.5, 26.5], [99.5, 4.0], [129.0, 35.0]],
    notes: 'Kuwait crude is major Korean import; highest Hormuz sensitivity.',
  },
  {
    id: 'qatar-south_korea-lng',
    supplierId: 'qatar',
    importerId: 'south_korea',
    product: 'lng',
    dependencyPct: 12,
    routeExposure: 66,
    corridor: 'Ras Laffan to Korean LNG terminals via Hormuz',
    chokepoints: ['hormuz_strait', 'malacca_strait'],
    waypointPositions: [[51.2, 25.4], [56.5, 26.5], [99.5, 4.0], [129.0, 35.0]],
    notes: 'Qatar LNG is critical for Korean gas security; dual chokepoint exposure.',
  },
  // EU routes
  {
    id: 'norway-eu-crude',
    supplierId: 'norway',
    importerId: 'eu',
    product: 'crude',
    dependencyPct: 25,
    routeExposure: 28,
    corridor: 'Norwegian North Sea to NW European refineries',
    chokepoints: ['english_channel', 'bosphorus'],
    waypointPositions: [[8.5, 60.5], [0.0, 55.0], [5.0, 52.0]],
    notes: 'Low-risk pipeline/tanker route; North Sea weather is primary disruption factor.',
  },
  {
    id: 'russia-eu-crude',
    supplierId: 'russia',
    importerId: 'eu',
    product: 'crude',
    dependencyPct: 15,
    routeExposure: 55,
    corridor: 'Baltic / Black Sea loaders to NW European refineries',
    chokepoints: ['bosphorus', 'danish_straits'],
    waypointPositions: [[37.6, 55.8], [29.0, 41.1], [12.0, 55.0], [5.0, 52.0]],
    notes: 'Sanctions-exposed route; payment and insurance complications drive disruption.',
  },
  {
    id: 'africa-eu-crude',
    supplierId: 'africa',
    importerId: 'eu',
    product: 'crude',
    dependencyPct: 12,
    routeExposure: 48,
    corridor: 'Nigeria / Libya to Mediterranean refineries',
    chokepoints: ['suez', 'bab_el_mandeb', 'gibraltar'],
    waypointPositions: [[3.4, 6.5], [32.3, 30.5], [10.0, 36.0], [5.0, 52.0]],
    notes: 'African barrels diversify Gulf exposure; Red Sea and Mediterranean transit risks.',
  },
  // Taiwan routes
  {
    id: 'saudi-taiwan-crude',
    supplierId: 'saudi_arabia',
    importerId: 'taiwan',
    product: 'crude',
    dependencyPct: 30,
    routeExposure: 74,
    corridor: 'Ras Tanura to Kaohsiung via Strait of Hormuz',
    chokepoints: ['hormuz_strait', 'malacca_strait'],
    waypointPositions: [[50.2, 26.6], [56.5, 26.5], [99.5, 4.0], [120.3, 22.6]],
    notes: 'Core Gulf crude for Taiwanese refineries; extreme sensitivity to Hormuz closure.',
  },
  {
    id: 'russia-taiwan-crude',
    supplierId: 'russia',
    importerId: 'taiwan',
    product: 'crude',
    dependencyPct: 10,
    routeExposure: 40,
    corridor: 'Russian Far East to Kaohsiung',
    chokepoints: ['malacca_strait'],
    waypointPositions: [[132.0, 43.0], [125.0, 30.0], [120.3, 22.6]],
    notes: 'Short-haul Russian crude; Pacific route avoids Gulf chokepoints.',
  },
  // Thailand routes
  {
    id: 'middle_east-thailand-crude',
    supplierId: 'saudi_arabia',
    importerId: 'thailand',
    product: 'crude',
    dependencyPct: 25,
    routeExposure: 65,
    corridor: 'Gulf to Laem Chabang via Strait of Hormuz',
    chokepoints: ['hormuz_strait', 'malacca_strait'],
    waypointPositions: [[50.2, 26.6], [56.5, 26.5], [99.5, 4.0], [100.9, 13.5]],
    notes: 'Thai refinery feedstock; dual chokepoint exposure via Gulf.',
  },
  // Vietnam routes
  {
    id: 'middle_east-vietnam-crude',
    supplierId: 'saudi_arabia',
    importerId: 'vietnam',
    product: 'crude',
    dependencyPct: 20,
    routeExposure: 62,
    corridor: 'Gulf to Nha Trang via Strait of Hormuz',
    chokepoints: ['hormuz_strait', 'malacca_strait'],
    waypointPositions: [[50.2, 26.6], [56.5, 26.5], [99.5, 4.0], [109.2, 12.2]],
    notes: 'Vietnam refinery feedstock; growing import dependency.',
  },
];

export const ENERGY_SUPPLY_NETWORK_SOURCE =
  'Modeled global energy import-dependency network from public trade patterns (EIA, IEA, World Bank) and ORION chokepoint registry; percentages are rounded planning weights, not customs declarations.';

export const IMPORTER_COUNTRY_CONFIG = [
  { code: 'IN', name: 'India', fuelMode: 'oil' as const, region: 'south_asia' },
  { code: 'CN', name: 'China', fuelMode: 'both' as const, region: 'east_asia' },
  { code: 'JP', name: 'Japan', fuelMode: 'both' as const, region: 'east_asia' },
  { code: 'KR', name: 'South Korea', fuelMode: 'both' as const, region: 'east_asia' },
  { code: 'EU', name: 'European Union', fuelMode: 'both' as const, region: 'europe' },
  { code: 'TW', name: 'Taiwan', fuelMode: 'both' as const, region: 'east_asia' },
  { code: 'TH', name: 'Thailand', fuelMode: 'oil' as const, region: 'southeast_asia' },
  { code: 'VN', name: 'Vietnam', fuelMode: 'oil' as const, region: 'southeast_asia' },
  { code: 'SG', name: 'Singapore', fuelMode: 'oil' as const, region: 'southeast_asia' },
  { code: 'US', name: 'United States', fuelMode: 'both' as const, region: 'americas' },
] as const;
